modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
[[mods]]
# The modid of the mod
modId = "pixelmongocinematic"
version = "${file.jarVersion}"
displayName = "PixelmonGo Cinematics"
logoFile = "examplemod.png"
credits = "PixelmonGo - AlphaDesnoc" 
authors = "AlphaDesnoc" 
description = '''
Un mod de cinematics pour PixelmonGo
'''
[[dependencies.pixelmongocinematic]] 
modId = "forge"
mandatory = true 
versionRange = "[36,)" 
ordering = "NONE"
side = "BOTH"
[[dependencies.pixelmongocinematic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"